### ISSUE TITLE
X and Y Axis Labels switched in parallel_analysis

### ISSUE THREAD

**Issue by daenemarque** [wjschne/WJSmisc#1]
Could you please look into the axis labels of the plot returned by parallel_analysis? I think the Axis Labels should be switched, so that the Label "Factors" (or Components) is on the X Axis, and the label "Eigenvalues" on the Y Axis.
https://github.com/wjschne/WJSmisc/blob/660f9747017bd3fb8f06bed3df55473f18db04cc/R/main.R#L608
https://github.com/wjschne/WJSmisc/blob/660f9747017bd3fb8f06bed3df55473f18db04cc/R/main.R#L609

Thank you :-)

**Comment by wjschne** [comment]
Fixed! Thank you!
